### ISSUE TITLE
Vehicles problem

### ISSUE THREAD

**Issue by ShazyLV** [JericoFX/qb_realparkingBY-JERICOFX#1]
Hello. When people drive with civilan vehicles then after 5min all vehicles clear on map. On ESX this problem not, only QBus
How can i fix this problem? Thanks

**Comment by JericoFX** [comment]
Clean on map? Or close to the parking?

**Comment by ShazyLV** [comment]
Yeah. Now i know problem. When people drive with vehicle then another user connecting to server and select character then all vehicles refresh and civilian vehicles lost.

**Comment by JericoFX** [comment]
what you can do is coment this function https://github.com/JericoFX/qb_realparkingBY-JERICOFX/blob/master/client/main.lua#L247 and here https://github.com/JericoFX/qb_realparkingBY-JERICOFX/blob/master/client/main.lua#L181 , modify that function to reduce the radius or simply tell everyone not get close to that places
